COLUMNS:
  price: int64
  area: int64
  bedrooms: int64
  bathrooms: int64
  stories: int64
  mainroad: object
  guestroom: object
  basement: object
  hotwaterheating: object
  airconditioning: object
  parking: int64
  prefarea: object
  furnishingstatus: object
TARGET_COLUMN:
  name: target